
export const FILTER_SELECTED = 'FILTER_SELECTED';
export const FILTER_INVALIDATED = 'FILTER_INVALIDATED';
export const CHARACTERS_REQUEST = 'CHARACTERS_REQUEST';
export const CHARACTERS_SUCCESS = 'CHARACTERS_SUCCESS';
export const CHARACTERS_FAILURE = 'CHARACTERS_FAILURE';
// export const RECEIVE_CHARACTERS = 'RECEIVE_CHARACTERS';
